### ISSUE TITLE
instagram 视频分享bug

### ISSUE THREAD

**Issue by youusername** [SongJiaqiang/VideoShareKit#1]
点击instagram分享后，跳转到instagram后不是选择分享的视频，总是选择第一个。

**Comment by SongJiaqiang** [comment]
没毛病，Ins分享就是先把视频/图片保存到相册，然后跳转到Ins app的分享页面，默认选中第一个视频/图片，也就是刚保存的那一个素材。

**Comment by youusername** [comment]
感谢回复，我已经发现这个问题了。
